// 9/src/app/app.component.ts
import { Component } from '@angular/core';

interface Organizer {
  name: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  name = 'Igor Halfeld';

  typescriptBrOrganizers: Organizer[] = [
    { name: 'Lucas' },
    { name: 'Vitor' },
    { name: 'Roz' },
  ];

  greeting(name: string): void {
    this.name = name;
  }
}

<div>
  <h1>Hello, {{ name }}</h1>
  <ul>
    <li *ngFor="let organizer of typescriptBrOrganizers">
      {{ organizer.name }}
    </li>
  </ul>
  <button (click)="greeting('TypescriptBR')" >Say Hello!</button>
</div>

// 7/src/App.tsx
import React, { useState } from 'react';

interface Organizer {
  name: string,
}

const App: React.FC = (): JSX.Element => {
  const [name, setName]: [string, Function] = useState('Igor Halfeld');

  function greeting(name: string): void {
    setName(name);
  }

  const typescriptBrOrganizers: Organizer[] = [
    { name: 'Lucas' },
    { name: 'Vitor' },
    { name: 'Roz' },
  ];

  return (
    <React.Fragment>
      <h1>Hello, {name}</h1>
      <ul>
        {
          typescriptBrOrganizers.map(organizer => (
            <li>{organizer.name}</li>
          ))
        }
      </ul>
      <button onClick={() => greeting('TypescriptBR')}>Say hello!</button>
    </React.Fragment>
  );
};

export default App;
