// 7/src/App.tsx
import React, { useState } from 'react';

interface Organizer {
  name: string,
}

const App: React.FC = (): JSX.Element => {
  const [name, setName]: [string, Function] = useState('Igor Halfeld');

  function greeting(name: string): void {
    setName(name);
  }

  const typescriptBrOrganizers: Organizer[] = [
    { name: 'Lucas' },
    { name: 'Vitor' },
    { name: 'Roz' },
  ];

  return (
    <React.Fragment>
      <h1>Hello, {name}</h1>
      <ul>
        {
          typescriptBrOrganizers.map(organizer => (
            <li>{organizer.name}</li>
          ))
        }
      </ul>
      <button onClick={() => greeting('TypescriptBR')}>Say hello!</button>
    </React.Fragment>
  );
};

export default App;

// 8/src/App.vue
<template>
  <div>
    <h1>Hello, {{ name }}</h1>
    <ul>
      <li v-for="organizer in typescriptBrOrganizers" :key="organizer.name">
        {{ organizer.name }}
      </li>
    </ul>
    <button @click="greetings('TypescriptBR')">Say hello!</button>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

interface Organizer {
  name: string,
}

export default Vue.extend({
  name: 'App',
  data() {
    return {
      name: 'Igor Halfeld',
      typescriptBrOrganizers: [
        { name: 'Lucas' },
        { name: 'Vitor' },
        { name: 'Roz' },
      ] as Organizer[],
    };
  },
  methods: {
    greetings(name: string) {
      this.name = name;
    },
  },
});
</script>
